# Generated by Django 4.2 on 2023-05-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
                ('manufacturer', models.CharField(max_length=75)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.categorymodel')),
            ],
        ),
    ]
